package edu.incense.android.datatask.data;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * This class is used to represent the data that is generated by the gyroscope sensor
 * Created by xilef on 10/26/2016.
 */
public class GyroscopeData extends Data {
    private float x; // Rotation around the x axis in rad/s
    private float y; // Rotation around the y axis in rad/s
    private float z; // Rotation around the z axis in rad/s

    /**
     * Creates an instance of the GyroscopeData class.
     */
    public GyroscopeData() {
        super(DataType.GYROSCOPE);
        x = 0;
        y = 0;
        z = 0;
    }

    /**
     * Creates an instance of the GyroscopeData class.
     *
     * @param x: The value of the x axis.
     * @param y: The value of the y axis.
     * @param z: The value of the z axis
     */
    public GyroscopeData(float x, float y, float z) {
        super(DataType.GYROSCOPE);
        setX(x);
        setY(y);
        setZ(z);
    }

    /**
     * Return the date and time the data contained by this class was generated.
     *
     * @return: The date and time as string in YYYY-MM-DD HH:MM:SS format.
     */
    public String getDataDateTime() {
        return new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS").format(new Date(super.getTimestamp()));
    }

    /**
     * Returns the current value of the x axis
     *
     * @return: the current value of the x axis
     */
    public float getX() {
        return x;
    }

    /**
     * Sets the value of the x axis
     *
     * @param x: the value of the x axis
     */
    public void setX(float x) {
        this.x = x;
    }

    /**
     * Returns the current value of the y axis value.
     *
     * @return: the y axis value
     */
    public float getY() {
        return y;
    }

    /**
     * Sets the value for the y axis
     * @param y: The value of the y axis
     */
    public void setY(float y) {
        this.y = y;
    }

    /**
     * Returns the value of the z axis
     * @return: The value of the z axis
     */
    public float getZ() {
        return z;
    }

    /**
     * Set the value of the z axis
     * @param z: the value of the z axis.
     */
    public void setZ(float z) {
        this.z = z;
    }

    /**
     * This function overrides the toString method, so when invoked returns a string that contains
     * the three values that this class holds (x, y and z axis).
     * @return: A string containing the three axis values.
     */
    @Override
    public String toString() {
        return "x: " + Float.toString(x) + ", y: " + Float.toString(y) + ", z: " + Float.toString(z);
    }
}
