package edu.incense.android.datatask.data;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * This classes represents the data that is generated by the OrientationSensor.
 * Created by xilef on 10/26/2016.
 */
public class OrientationData extends Data {
    private float x;
    private float y;
    private float z;

    /**
     * Creates a new instance of the OrientationData class.
     */
    public OrientationData(){
        super(DataType.ORIENTATION);
        x = 0;
        y = 0;
        z = 0;
    }

    /**
     * Creates a new instance of the OrientationDdata class.
     * @param x: The angle value of the x axis of the orientation data (Pitch) in degrees.
     * @param y: The angle value of the y axis of the orientation data (Roll) in degrees.
     * @param z: The angle value of the z axis of the orientation data (azimuth) in degrees.
     */
    public OrientationData(float x, float y, float z){
        super(DataType.ORIENTATION);
        setX(x);
        setY(y);
        setZ(z);
    }

    /**
     * This function returns the date and time in which the data contained by an instance of this
     * class was generated as a string in the format yyyy-MM-dd HH:mm:ss.
     * @return The date and time as a string.
     */
    public String getDataDateTime(){
        return new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS").format(new Date(super.getTimestamp()));
    }

    /**
     * Returns the angle value of the x axis of the orientation data (Pitch) in degrees
     * @return The angle value of the x axis of the orientation data (Pitch) in degrees
     */
    public float getX() {
        return x;
    }

    /**
     * Establishes the angle value of the x axis (Pitch) in degrees
     * @param x The x angle value.
     */
    public void setX(float x) {
        this.x = x;
    }

    /**
     * Returns the angle value of the y axis of the orientation data (Roll) in degrees.
     * @return The angle value of the y axis of the orientation data (Roll) in degrees.
     */
    public float getY() {
        return y;
    }

    /**
     * Establishes the angle value of the y axis (Roll) in degrees.
     * @param y The y angle value
     */
    public void setY(float y) {
        this.y = y;
    }

    /**
     * Returns the angle value of the z axis of the orientation data (azimuth) in degrees.
     * @return The angle value of the z axis of the orientation data (azimuth) in degrees.
     */
    public float getZ() {
        return z;
    }

    /**
     * Etablishes the angle value of the z axis (Azimuth) in degrees
     * @param z The z angle value
     */
    public void setZ(float z) {
        this.z = z;
    }

    /**
     * Returns the x, y and z angle as a string.
     * @return String containing the x, y and z angle values.
     */
    @Override
    public String toString() {
        return "x: " + Float.toString(x) + ", y: " + Float.toString(y) + ", z: " + Float.toString(z);
    }
}
